services:
  - type: web
    name: portal-del-estudiante
    env: node
    nodeVersion: 20
    buildCommand: npm install && npm run build
    startCommand: npm start
    publishDirectory: dist/client
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    databaseName: websocketchat
    user: postgres 