CREATE TABLE employees (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  document_number VARCHAR(20) NOT NULL,
  birth_date DATE NOT NULL,
  cell_phone VARCHAR(20),
  phone VARCHAR(20),
  address TEXT,
  locality VARCHAR(100),
  email VARCHAR(255) NOT NULL,
  blood_type VARCHAR(10),
  eps VARCHAR(100),
  pension_fund VARCHAR(100),
  severance_fund VARCHAR(100),
  arl VARCHAR(100),
  compensation_fund VARCHAR(100),
  position VARCHAR(100),
  emergency_contact VARCHAR(255),
  emergency_contact_relationship VARCHAR(100),
  emergency_contact_phone VARCHAR(20),
  children INTEGER,
  contract_start_date DATE,
  contract_end_date DATE,
  salary DECIMAL(10, 2),
  payment_entity VARCHAR(100),
  account_number VARCHAR(50),
  is_active BOOLEAN DEFAULT true,
  arl_affiliation_date DATE,
  arl_disaffiliation_date DATE,
  eps_affiliation_date DATE,
  eps_disaffiliation_date DATE,
  compensation_fund_affiliation_date DATE,
  compensation_fund_disaffiliation_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 